const Images = {
  splashBackgroundImage: require("../assets/backgroundImage.png"),
  logo: require("../assets/logo.png"),
  loginImageBackground: require("../assets/loginBG.png"),
  appleIcon: require("../assets/appleIcon.png"),
  googleIcon: require("../assets/googleIcon.png"),
  facebookIcon: require("../assets/facebookIcon.png"),
  calenderIcon: require("../assets/calenderIcon.png"),
  locationIcon: require("../assets/locationIcon.png"),
  timeIcon: require("../assets/timeIcon.png"),
  seatIcon: require("../assets/seatIcon.png"),
  callIcon: require("../assets/callIcon.png"),
  mailIcon: require("../assets/mailIcon.png"),
  paymentCards: require("../assets/paymentCards.png"),
  appleIcon: require("../assets/appleIcon.png"),
  timer: require("../assets/timer.png"),
  questionsIcon: require("../assets/questionIcon.png"),
  calendarActiveIcon: require("../assets/calenderActiveIcon.png"),
  timeActiveIcon: require("../assets/timeActiveIcon.png"),
  bookingActiveIcon: require("../assets/bookingActiveIcon.png"),
  bookingInActiveicon: require("../assets/bookingInActive.png"),
  placesActiveIcon: require("../assets/placeInactive.png"),
  placesInActiveIcon: require("../assets/placesInActiveIcon.png"),
  reviewActiveIcon: require("../assets/reviewActive.png"),
  reviewInActiveIcon: require("../assets/reviewInActive.png"),
  hacksActiveIcon: require("../assets/hacksActive.png"),
  hacksInActiveIcon: require("../assets/hacksInActive.png"),
  uploadIcon: require("../assets/uploadIcon.png"),
  settingIcon: require("../assets/settingIcon.png"),
  passwordIcon: require("../assets/passwordIcon.png"),
  supportIcon: require("../assets/supportIcon.png"),
  feedbackIcon: require("../assets/feedbackIcon.png"),
  activityIndicator: require("../assets/activityIndicator.png"),
  errorIcon: require("../assets/errorIcon.png"),
  noUserIcon: require("../assets/noUserIcon.png"),
  homeIcon: require("../assets/homeIcon.png"),
  FAQ:require('../assets/FAQ.png'),
  checkIcon:require('../assets/checkIcon.png'),
  homeActiveIcon:require('../assets/HomeActiveIcon.png'),
  homeInActiveIcon:require('../assets/HomeInActiveIcon.png')
};
export default Images;
